### ISSUE TITLE
Suggested configuration leads to failing proof

### ISSUE THREAD

**Issue by treiher** [HeisenbugLtd/spat#50]
**Describe the bug**
The `--suggest` option has multiple issues:

1. The determined steps seem to be wrong. In my example they were either too high or too low.
2. The determined timeout is too low.
3. Setting `--steps` and `--timeout` using `Prover_Switches` has no effect.

**To Reproduce**
So far I'm using [sparkprof](https://github.com/Componolit/sparkprof) to determine the maximum number of steps. Here is an example (the two used files can be found [here](https://github.com/Componolit/RecordFlux/tree/410a9daf7e863891c1be301dbb13bbce0300cde7/generated)):

```Console
$ sparkprof -Ptest --level=4
Phase 1 of 2: generation of Global contracts ...
Phase 2 of 2: flow analysis and proof ...
------------------------------------------------------
UNIT                 MAX STEPS    MAX TIME  TOTAL TIME
rflx-rflx_arithmetic  90761 steps    21.0 s    54.2 s
ALL                   90761 steps    21.0 s    54.2 s
```

Based on that output I would add the following to the project file:

```Ada
   package Prove is
      for Proof_Switches ("rflx-rflx_arithmetic.ads") use ("--steps=90761");
      for Proof_Switches ("rflx-rflx_arithmetic.adb") use ("--steps=90761");
   end Prove;
```

After adding these switches to the project the project can still be proven. If the steps value is changed to 90760, `gnatprove` fails as expected.

SPAT suggests quite different options:

```Console
package Prove is
   for Prover_Switches ("rflx-rflx_arithmetic.adb") use ("--provers=CVC4", "--steps=82085", "--timeout=1");
   for Prover_Switches ("rflx-rflx_arithmetic.ads") use ("--provers=CVC4", "--steps=3191607", "--timeout=21");
end Prove;
```

When I use the proposed switches, `gnatprove` fails:

```Console
$ gnatprove -Ptest               
Phase 1 of 2: generation of Global contracts ...
Phase 2 of 2: flow analysis and proof ...
rflx-rflx_arithmetic.adb:11:13: medium: divide by zero might fail [possible explanation: precondition of subprogram at rflx-rflx_arithmetic.ads:16 should mention Value]
[...]
```

This seems to have multiple reasons:
- `--steps` and `--timeout` seem to be ignored in `Prover_Switches`. They have an effect as soon as I replace `Prover_Switches` by `Proof_Switches` (and remove `--provers`).
- The timeout seems to be to low. Many failing checks vanish when `--timeout` is removed.
- The suggested steps for `rflx-rflx_arithmetic.adb` are too low. The remaining failing check vanishes when the steps are increased to 90761.

**Comment by Jellix** [comment]
I see what you mean, and obviously I booboo'd with the configuration option names.

I'll look into it. Not having much time at the moment, so that might take a while, so don't hold your breath.

**Comment by Jellix** [comment]
Hello @treiher, could you do me a favor and run `run_spat` with the `--verbose` (`-v`) option added? That should spit out some timing/steps data per prover. Maybe this at least clears up why it comes up with these unexpected values.

**Comment by treiher** [comment]
Sure, here is the output:

```Console
Debug: GNAT project loaded in 19.3 ms.
Debug: Found "rflx-rflx_arithmetic.adb"...Debug: "rflx-rflx_arithmetic.spark" added to index.
Debug: Found "rflx-rflx_arithmetic.ads"...Debug: "rflx-rflx_arithmetic.spark" already in index.
Debug: Found "rflx.ads"...Debug: "rflx.spark" added to index.
Debug: Search completed in 71.5 µs, 2 files found.
Debug: Using up to 16 parsing threads.
Debug: Queuing "/home/tr/tmp/build/gnatprove/rflx-rflx_arithmetic.spark"...
Debug: Queuing "/home/tr/tmp/build/gnatprove/rflx.spark"...
Debug: Picking up results...
Debug: "/home/tr/tmp/build/gnatprove/rflx.spark"...ok.
Debug: "/home/tr/tmp/build/gnatprove/rflx-rflx_arithmetic.spark"...ok.
Debug: Parsing completed in 4.1 ms.
Debug: File version: GNAT_CE_2020
Debug: File version: GNAT_CE_2020
Debug: Reading completed in 1.5 ms.
Debug: Cut off point set to 0.0 s.
Warning: You requested a suggested prover configuration.
Warning: This feature is highly experimental.
Warning: Please consult the documentation.
Debug: rflx-rflx_arithmetic.adb
Debug:   CVC4
Debug:     t(Success) 0.0 s
Debug:     t(Failed)  0.0 s
Debug:     T(Success) 0.0 s
Debug:     S(Success) 82085
Debug: rflx-rflx_arithmetic.ads
Debug:   CVC4_CE
Debug:     t(Success) 0.0 s
Debug:     t(Failed)  0.0 s
Debug:     T(Success) 0.0 s
Debug:     S(Success) 0
Debug:   CVC4
Debug:     t(Success) 20.5 s
Debug:     t(Failed)  0.0 s
Debug:     T(Success) 20.5 s
Debug:     S(Success) 3191607

package Prove is
   for Prover_Switches ("rflx-rflx_arithmetic.adb") use ("--provers=CVC4", "--steps=82085"", "--timeout=1");
   for Prover_Switches ("rflx-rflx_arithmetic.ads") use ("--provers=CVC4,CVC4_CE", "--steps=3191607"", "--timeout=21");
end Prove;
```

**Comment by Jellix** [comment]
Thank you.

That seems to confirm the decisions SPAT did. As you can see from the debug output, the values do seem to make sense at first glance (reported maximum number of steps for successful proof for the body is `82085`, and `3191607` for the spec, and so are the timeout suggestions based on the maximum successful proof time for each file).

So I am guessing the error is on my side having the wrong assumptions about how to interpret the values properly. I'll investigate.

One remark though: The zero times may indicate that you ran `run_spat` after a non-pristine run of gnatprove? This is a [known limitation](https://github.com/HeisenbugLtd/spat/blob/master/README.md#tool-limitations) of the tool, because in such a case, `gnatprove` does not fill in any timing information for proofs it already proved in previous runs, so SPAT would wrongly assume a zero time for all proofs.

**Comment by treiher** [comment]
I just saw that you replaced `Prover_Switches` by `Proof_Switches` in 2430b8c1cc2a213009c5e001df2a39d1a7eac539. That doesn't work, as `--provers` is not recognized by gnatprove when used in `Proof_Switches`:

```Console
gnatprove: unrecognized option '--provers=CVC4'
```

> The zero times may indicate that you ran run_spat after a non-pristine run of gnatprove?

You seem to be right. I am aware of this limitation, but I did not think about it when I posted the output..

```Ada
Debug: rflx-rflx_arithmetic.adb
Debug:   CVC4
Debug:     t(Success) 530.0 ms
Debug:     t(Failed)  0.0 s
Debug:     T(Success) 530.0 ms
Debug:     S(Success) 82085
Debug: rflx-rflx_arithmetic.ads
Debug:   CVC4
Debug:     t(Success) 53.4 s
Debug:     t(Failed)  0.0 s
Debug:     T(Success) 20.5 s
Debug:     S(Success) 3191607

**Comment by Jellix** [comment]
Silly me, it's `--prover`, not `--provers`, I failed to properly [RTFM](https://docs.adacore.com/spark2014-docs/html/ug/en/appendix/project_attributes.html):

> Only the following switches are allowed for file-specific switches: --steps, --timeout, --memlimit, --proof, --prover, --level, --no-counterexample, --no-inlining, --no-loop-unrolling

On the good news side, I think I have a grasp on what's going on with the wrong suggested steps stuff. If my hunch is right, that should be quite easy to fix. Still have to figure out how the timeout is applied if specified for spec and body separately.

**Comment by yannickmoy** [comment]
`Proof_Switches` is the correct name to pass switches to GNATprove either globally or for specific units: http://docs.adacore.com/live/wave/spark2014/html/spark2014_ug/en/appendix/project_attributes.html

Also note that a unit is analyzed all at once, so specifying switches for both "rflx-rflx_arithmetic.adb" and "rflx-rflx_arithmetic.ads" is not useful. In that case, only the second set of switches will be used.

Finally, you seem to indicate above that `--steps` and `--timeout` have no effect when given in `Proof_Switches`, is that related to the above issue? Otherwise, please open a ticket on spark@adacore.com as we are not aware of that problem.

**Comment by treiher** [comment]
> Also note that a unit is analyzed all at once, so specifying switches for both "rflx-rflx_arithmetic.adb" and "rflx-rflx_arithmetic.ads" is not useful. In that case, only the second set of switches will be used.

I also was not aware of that. Since you have to specify the full file name, this gives the impression that you have to state both. Thanks for the clarification.

> Finally, you seem to indicate above that `--steps` and `--timeout` have no effect when given in `Proof_Switches`, is that related to the above issue? Otherwise, please open a ticket on [spark@adacore.com](mailto:spark@adacore.com) as we are not aware of that problem.

`--steps` and `--timeout` works fine for me in `Proof_Switches`. They had no effect because a incorrect name was used.

**Comment by Jellix** [comment]
> Also note that a unit is analyzed all at once, so specifying switches for both "rflx-rflx_arithmetic.adb" and "rflx-rflx_arithmetic.ads" is not useful. In that case, only the second set of switches will be used.

Thanks for the clarification, I will adjust the code accordingly.

Meanwhile, if you have the time, could you take a look at [this wiki page](https://github.com/HeisenbugLtd/spat/wiki/Investigating-issue-%2350) where I put down my braindump why the steps value SPAT is currently using seems so vastly different from what `gnatprove` considers steps?

**Comment by kanigsson** [comment]
The reason is that internally, there are two notions of steps in SPARK. Each prover has a different behavior wrt to steps, so we present a unified steps count to the user. For each prover (alt-ergo, cvc4, z3), we have a different affine relation (a*x + b) that maps the unified steps to the prover steps. For example, for cvc4 the user-provided step limit is "stretched" by setting a = 35 and b = 15000, see also https://github.com/AdaCore/why3/blob/master/src/gnat/gnat_config.ml#L538 .The aim is to have not too different running times with steps across provers.

I'm assuming `sparkprof` is based on the gnatprove command line output and `gnatprove.out`, while `SPAT` parses the `.spark` files. That would explain the discrepancy.

Now the `.spark` files actually *mix* the two notions, which is not great. The check_tree VCs contain the prover steps, and the "stats" object contains aggregated max steps for each prover, for the entire "check_tree".

The fact that the check_tree contains prover steps is a mistake, and we will fix it in SPARK, but in the meantime you should probably use the stats object, or do the backwards conversion yourself using the values in `gnat_config.ml` above, for each prover.

**Comment by Jellix** [comment]
> The fact that the check_tree contains prover steps is a mistake, and we will fix it in SPARK, but in the meantime you should probably use the stats object, or do the backwards conversion yourself using the values in `gnat_config.ml` above, for each prover.

Thank you, that clarifies the issue. :)

**Comment by Jellix** [comment]
@treiher just as a heads-up: I think I have a fix. I still want to manually verify it with the test data I have, but so far it's looking good.

Also, while fixing the issue I noticed a **major bug** that renders the whole output pretty much useless even without the issues discussed here. In short: Collected proof data gets associated with unrelated files and the output is based on that completely bogus result.

**Comment by Jellix** [comment]
Ok, everything is looking fine, I consider that fixed now.

**Comment by treiher** [comment]
Thanks for the fast fix! It works fine now for my example.

**Comment by Jellix** [comment]
Great to hear. :)

**Comment by kanigsson** [comment]
The development version of SPARK now puts the proper converted steps into the "check_tree" data of the .spark files.
