### ISSUE TITLE
Incorrect warning about missing timings

### ISSUE THREAD

**Issue by kanigsson** [HeisenbugLtd/spat#6]
When running SPAT on a toy project, I get warnings like these:
```
Warning: Expected field "gnatwhy3.run_vcs" not present!
Warning: Expected field "gnatwhy3.register_vcs" not present!
Warning: Expected field "gnatwhy3.schedule_vcs" not present!
```
But it's expected to have such missing fields, it just means the corresponding phase wasn't run at all. For the statistics, the tool should assume the phase took no time (0s).

**Comment by kanigsson** [comment]
More generally, concerning timings, it seems strange to pick just those three to account for "proof". In fact all timings prefixed with "gnatwhy3" could be assigned to "proof", and all the prover timings as well.

**Comment by Jellix** [comment]
This was a quick fix related to the changes in the file format in the 2020 community release (see spat-timing_items.adb). The 2019 version had a field "proof" which disappeared in 2020. Guess I have to bite the bullet and instead of relying on the information in the timings object just add all times from the single proofs for the summary output.

**Comment by Jellix** [comment]
Thanks for the report. I implemented your suggested changes and even found a defect in the calculation of the total proof time.

The warnings should be gone now, and the reported timings in the summary should be more accurate.
